spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true
